### PR TITLE
Update project.clj dependency

### PR DESCRIPTION
**Pull request by tuddman**
protobuf-java `3.18.0`

### CODE REVIEW

**Comment by tuddman** [comment]
reference https://github.com/protojure/lib/issues/93

**Comment by ghaskins** [comment]
@tuddman sorry, I do a poor job of noticing github notifications.  If you update your DCO I can merge this.  Best bet to get my attention is to hit me up on #protojure on the Clojurians Slack

**Comment by tuddman** [comment]
@ghaskins  ok, DCO _signed_

**Comment by ghaskins** [comment]
Superceded by https://github.com/protojure/google.protobuf/commit/e6cfcac515705046fce05e5f8cdea5546a48fa4a

**Pull request closed without merging**
